POST http://localhost:3000/ads
Content-Type: application/json

 {
      "title": "annonce7",
      "description":"description annonce 5 ",
      "owner": "jaki",
      "price": 1001,
      "picture":"https://www.google.com/images/branding/googlelogo/1x/googlelogo_light_color_272x92dp.png ",
      "location": "rome",
      "category": 2,
      "tags": [{"id":1}]
    }
    